name: minha_loja
description: A new Flutter project. Created by Slidy
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

## Slidy Scripts 
vars: 
    clean: flutter clean
    get: flutter pub get
    runner: flutter pub run build_runner
    apk: flutter build apk --split-per-abi
scripts: 
    build: $runner build
    build_: $clean & $get & $runner build --delete-conflicting-outputs
    watch: $clean & $get & $runner watch
    watch_: $clean & $get & $runner watch --delete-conflicting-outputs
    apk: $apk

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  # Aplicar máscaras aos TextFields e Strings
  easy_mask: ^1.1.4
  # Validar cpf e cnpj
  cpfcnpj: ^1.0.3
  # Escolher imagens da biblioteca de imagens e tirar fotos com a câmera
  image_picker: ^0.6.7+17
  # Permite encontrar locais comumente usados ​​no sistema de arquivos (Suporta iOS, Android, Linux e MacOS)
  path_provider: ^1.6.24
  # Http client
  dio: ^3.0.10
  # Gerenciamento de estado
  mobx: ^1.2.1+4
  # Fornece o widget Observer que escuta os observáveis ​​e reconstrói automaticamente nas mudanças.
  flutter_mobx: ^1.1.0+2
  # Rotas, injeção de dependências
  flutter_modular: ^2.0.1
  # Pacote Font Awesome Icon
  font_awesome_flutter: ^8.10.0
  # Snackbars, dialogs, ModalSheets in a single provider.
  asuka: ^1.0.4
  # Permite solicitar permissões e verificar seus status
  permission_handler: ^5.0.1+1
  # Formata os inputs
  mask_text_input_formatter: ^1.2.1
  # Banco de dados de valores-chave leve e extremamente rápido escrito em Dart puro.
  hive: ^1.4.4+1
  # WooCommerce
  woocommerce: ^0.9.7
  # WordPress API
  wordpress_api: ^0.2.1+1
  # Carousel
  carousel_pro:
  flutter:
    sdk: flutter

dev_dependencies:
  # Mock
  mockito: ^4.1.3
  # Gerador de código p/ modular .g.dart
  modular_codegen: ^2.0.1
  # Gerador de código p/ mobx .g.dart
  mobx_codegen: ^1.1.2
  build_runner: ^1.10.11
  # Permite a implementação de testes unitários
  flutter_test:
    sdk: flutter 

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  assets:
    - assets/images/

  # Fontes
  fonts:
    - family: CartIcons
      fonts:
        - asset: assets/fonts/CartIcons.ttf